sudo: required
language: generic 
services: 
  - docker

before_install:
  - docker build -t motomaniak/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true motomaniak/docker-react npm run test -- --coverage