language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t motomaniak/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true motomaniak/docker-react npm run test

deploy: 
  prodiver: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-372424862330"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY